"""
This is a setup.py script generated by py2applet

Usage:
    python3 setup.py py2app
"""

from setuptools import setup

APP = ['ShopifyPazlsCsvConverter.py']
DATA_FILES = []
OPTIONS = {
    #'iconfile':'csvlogo',
    'argv_emulation': True,
    'packages': ['pathlib','tkinter','numpy','pandas']#,'tkinter.filedialog','numpy.core.numeric']
    }

#import pathlib as p
# import tkinter
# import tkinter.filedialog
# from numpy.core.numeric import NaN
# import pandas as pd
# import numpy as np

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)

